"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" 
" => General Configuration
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Enable filetype plugins
filetype plugin on
filetype indent on

" https://gist.github.com/rocarvaj/2513367
set nocompatible
syntax on
"http://stackoverflow.com/questions/5367760/vim-disabling-the-cursor-arrow-keys-but-only-for-navigation
" Disable Arrow keys in Escape mode
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

" set ruler for details of the file
set ruler
" Always display the status line, even if only one window is displayed
set laststatus=2
"set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l\ \ Column:\ %c
"https://www.linux.com/news/more-informative-status-line-vim
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
" Returns true if paste mode is enabled
function! HasPaste()
    if &paste
        return 'PASTE MODE  '
    endif
    return ''
endfunction


" Turn backup off, since most stuff is in SVN, git et.c anyway...
set nobackup
set nowb
set noswapfile

" http://vim.wikia.com/wiki/Example_vimrc
" Better command-line completion
" https://dougblack.io/words/a-good-vimrc.html
set incsearch           " search as characters are entered
set hlsearch            " highlight matches
set ignorecase          " Ignore case when searching
" turn off search highlight
nnoremap <leader><space> :nohlsearch<CR> 
set number 		" show line numbers
set showcmd             " show command in bottom bar"
set wildmenu            " visual autocomplete for command menu"
set lazyredraw 		" redraw only when we need to."
" move vertically by visual line
nnoremap j gj
nnoremap k gk

" No annoying sound on errors
" https://github.com/amix/vimrc/blob/master/vimrcs/basic.vim
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" Enable Zenburn color.
set t_Co=256
colors zenburn

" Opening multiple file
" http://vim.wikia.com/wiki/Project_browsing_using_find
set path=$PWD/**

" http://vim.wikia.com/wiki/Great_wildmode/wildmenu_and_console_mouse
set wildmenu
" set wildmode=list:longest,full
"

" https://stackoverflow.com/questions/3446320/in-vim-how-to-map-save-to-ctrl-s
" Map Ctrl + S to save a file, if terminal freezes press ctrl + Q
"
noremap <silent> <C-S>          :update<CR>
vnoremap <silent> <C-S>         <C-C>:update<CR>
inoremap <silent> <C-S>         <C-O>:update<CR>

" https://jeffkreeftmeijer.com/vim-number/
set number relativenumber


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Pathogen Plugin Configuration
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
execute pathogen#infect()
